/* BDR ERP - ENDEREÇAMENTO 3D REAL COMPLETO */
let scene,camera,renderer,controls,raycaster,mouse,objetosClicaveis=[],grupoLayout=null,gridHelper=null,enderecoSelecionado=null,visao2DAtiva=false,gradesAtivas=true;
function ir(pagina){window.location.href=pagina}function v(id){return String(document.getElementById(id)?.value||'').trim()}function n(id){return Number(v(id)||0)}function pad(num){return String(num).padStart(2,'0')}function db(){return window.client||window.supabaseClient||window.clientSupabase||globalThis.client}
function toast(msg){const el=document.getElementById('toast3d');if(!el)return;el.innerText=msg;el.classList.add('ativo');setTimeout(()=>el.classList.remove('ativo'),1800)}
function lerConfig(){return{rua:v('rua').toUpperCase()||'R1',faces:Math.max(1,n('faces')),prateleiras:Math.max(1,n('prateleiras')),colunas:Math.max(1,n('colunas')),niveis:Math.max(1,n('niveis')),caixas:Math.max(1,n('caixas')),tipoArea:v('tipoArea')||'GERAL'}}
function codigoEndereco(rua,face,prateleira,coluna,nivel,caixa){let codigo=`${rua}-F${face}-P${pad(prateleira)}-C${pad(coluna)}-N${nivel}`;if(Number(caixa)>1)codigo+=`-CX${caixa}`;return codigo.toUpperCase()}
function iniciarThree(){if(!window.THREE){alert('Three.js não carregou. Verifique sua internet/CDN.');return}const canvas=document.getElementById('threeCanvas');scene=new THREE.Scene();scene.background=new THREE.Color(0xf3f6fb);camera=new THREE.PerspectiveCamera(45,canvas.clientWidth/canvas.clientHeight,.1,2000);camera.position.set(18,16,22);renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(window.devicePixelRatio||1);renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.screenSpacePanning=false;controls.maxPolarAngle=Math.PI/2.15;controls.minPolarAngle=Math.PI/6;controls.minDistance=8;controls.maxDistance=60;controls.rotateSpeed=.8;controls.zoomSpeed=.9;controls.panSpeed=.8;controls.target.set(0,2,0);controls.update();raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();adicionarLuzes();adicionarPiso();adicionarParedes();adicionarGrades();renderer.domElement.addEventListener('click',selecionarObjeto3D);window.addEventListener('resize',redimensionarThree);animar()}
function adicionarLuzes(){scene.add(new THREE.AmbientLight(0xffffff,.72));const luz=new THREE.DirectionalLight(0xffffff,1.4);luz.position.set(18,24,12);luz.castShadow=true;luz.shadow.mapSize.width=2048;luz.shadow.mapSize.height=2048;scene.add(luz);const ponto=new THREE.PointLight(0xffffff,.6,80);ponto.position.set(-15,16,-12);scene.add(ponto)}
function criarTexturaPiso(){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d');ctx.fillStyle='#b7bcc5';ctx.fillRect(0,0,512,512);ctx.strokeStyle='rgba(255,255,255,.20)';ctx.lineWidth=2;for(let i=0;i<=512;i+=64){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,512);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(512,i);ctx.stroke()}for(let i=0;i<800;i++){ctx.fillStyle=`rgba(0,0,0,${Math.random()*0.08})`;ctx.fillRect(Math.random()*512,Math.random()*512,2,2)}const texture=new THREE.CanvasTexture(canvas);texture.wrapS=THREE.RepeatWrapping;texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(8,6);return texture}
function adicionarPiso(){const geo=new THREE.PlaneGeometry(80,60),mat=new THREE.MeshStandardMaterial({map:criarTexturaPiso(),roughness:.9,metalness:.05}),piso=new THREE.Mesh(geo,mat);piso.rotation.x=-Math.PI/2;piso.receiveShadow=true;piso.name='PISO';scene.add(piso)}
function adicionarParedes(){const mat=new THREE.MeshStandardMaterial({color:0xa6adb8,roughness:.85});const fundo=new THREE.Mesh(new THREE.BoxGeometry(80,12,.5),mat);fundo.position.set(0,6,-30);fundo.receiveShadow=true;scene.add(fundo);const esq=new THREE.Mesh(new THREE.BoxGeometry(.5,12,60),mat);esq.position.set(-40,6,0);esq.receiveShadow=true;scene.add(esq)}
function adicionarGrades(){gridHelper=new THREE.GridHelper(80,40,0xffcc00,0xd1d5db);gridHelper.position.y=.02;scene.add(gridHelper)}
function redimensionarThree(){if(!renderer||!camera)return;const canvas=renderer.domElement;camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();renderer.setSize(canvas.clientWidth,canvas.clientHeight,false)}
function animar(){requestAnimationFrame(animar);if(controls){if(controls.target.y<0)controls.target.y=0;if(camera.position.y<1.2)camera.position.y=1.2;controls.update()}renderer.render(scene,camera)}
function simularLayout(){limparLayout3D();const cfg=lerConfig();grupoLayout=new THREE.Group();grupoLayout.name='LAYOUT_BDR';scene.add(grupoLayout);objetosClicaveis=[];const espacamentoFace=7.2,espacamentoPrateleira=4.2;for(let face=1;face<=cfg.faces;face++){const z=(face-1)*espacamentoFace-((cfg.faces-1)*espacamentoFace/2);for(let prat=1;prat<=cfg.prateleiras;prat++){const x=(prat-1)*espacamentoPrateleira-((cfg.prateleiras-1)*espacamentoPrateleira/2);const rack=criarRack(cfg,face,prat);rack.position.set(x,0,z);grupoLayout.add(rack);criarTexto3D(`P${pad(prat)}`,x,4.3,z+1.65,grupoLayout)}criarTexto3D(`FACE ${face}`,-((cfg.prateleiras)*espacamentoPrateleira/2),5.1,z,grupoLayout)}criarMarcacoesRua(cfg);atualizarResumo();preencherTabela();gerarEtiquetas(false);resetCamera();toast('Layout 3D gerado com sucesso.')}
function limparLayout3D(){if(grupoLayout){scene.remove(grupoLayout);limparObjeto(grupoLayout)}grupoLayout=null;objetosClicaveis=[];enderecoSelecionado=null}
function limparObjeto(obj){obj.traverse(child=>{if(child.geometry)child.geometry.dispose();if(child.material){Array.isArray(child.material)?child.material.forEach(m=>m.dispose()):child.material.dispose()}})}
function criarRack(cfg,face,prateleira){const grupo=new THREE.Group(),largura=cfg.colunas*.62,altura=cfg.niveis*.72,profundidade=1.45;criarEstruturaRack(grupo,largura,altura,profundidade);criarPosicoesRack(grupo,cfg,face,prateleira,largura);return grupo}
function criarEstruturaRack(grupo,largura,altura,profundidade){const azul=new THREE.MeshStandardMaterial({color:0x0b4f93,roughness:.45,metalness:.45}),laranja=new THREE.MeshStandardMaterial({color:0xff7a00,roughness:.45,metalness:.35});const posteGeo=new THREE.BoxGeometry(.08,altura+.45,.08),vigaGeo=new THREE.BoxGeometry(largura+.35,.08,.10),profGeo=new THREE.BoxGeometry(.08,.08,profundidade+.20),xs=[-largura/2,largura/2],zs=[-profundidade/2,profundidade/2];xs.forEach(x=>zs.forEach(z=>{const poste=new THREE.Mesh(posteGeo,azul);poste.position.set(x,(altura+.45)/2,z);poste.castShadow=true;grupo.add(poste)}));for(let nivel=0;nivel<=Math.ceil(altura/.72);nivel++){const y=.32+nivel*.72;zs.forEach(z=>{const viga=new THREE.Mesh(vigaGeo,laranja);viga.position.set(0,y,z);viga.castShadow=true;grupo.add(viga)});xs.forEach(x=>{const vp=new THREE.Mesh(profGeo,laranja);vp.position.set(x,y,0);vp.castShadow=true;grupo.add(vp)})}}
function criarPosicoesRack(grupo,cfg,face,prateleira,largura){const livre=new THREE.MeshStandardMaterial({color:0x1f8f4a,roughness:.62,metalness:.05}),papel=new THREE.MeshStandardMaterial({color:0xb9854f,roughness:.78}),palletMat=new THREE.MeshStandardMaterial({color:0xd6d9de,roughness:.7}),boxGeo=new THREE.BoxGeometry(.48,.34,.88),palletGeo=new THREE.BoxGeometry(.54,.05,.94);for(let nivel=1;nivel<=cfg.niveis;nivel++)for(let coluna=1;coluna<=cfg.colunas;coluna++){const x=-largura/2+.31+(coluna-1)*.62,y=.34+(nivel-1)*.72,z=0,codigo=codigoEndereco(cfg.rua,face,prateleira,coluna,nivel,1);const pallet=new THREE.Mesh(palletGeo,palletMat);pallet.position.set(x,y-.19,z);pallet.castShadow=true;pallet.receiveShadow=true;grupo.add(pallet);const box=new THREE.Mesh(boxGeo,(coluna+nivel+prateleira)%3===0?papel:livre);box.position.set(x,y,z);box.castShadow=true;box.receiveShadow=true;box.userData={clicavel:true,codigo,rua:cfg.rua,face,prateleira,coluna,nivel,caixa:1,tipoArea:cfg.tipoArea,status:'LIVRE'};grupo.add(box);objetosClicaveis.push(box)}}
function criarMarcacoesRua(cfg){if(!grupoLayout)return;for(let face=1;face<=cfg.faces;face++){const z=(face-1)*7.2-(((cfg.faces-1)*7.2)/2);criarTexto3D(`${cfg.rua} / F${face}`,0,.05,z-2.3,grupoLayout,.32)}}
function criarTexto3D(texto,x,y,z,grupo,tamanho=.42){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='rgba(255,255,255,.92)';ctx.fillRect(0,0,512,128);ctx.strokeStyle='rgba(17,24,39,.25)';ctx.lineWidth=6;ctx.strokeRect(0,0,512,128);ctx.fillStyle='#111827';ctx.font='bold 54px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(texto,256,66);const texture=new THREE.CanvasTexture(canvas),material=new THREE.SpriteMaterial({map:texture}),sprite=new THREE.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(tamanho*4,tamanho,1);grupo.add(sprite)}
function selecionarObjeto3D(event){const rect=renderer.domElement.getBoundingClientRect();mouse.x=((event.clientX-rect.left)/rect.width)*2-1;mouse.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(objetosClicaveis,false);if(hits.length===0)return;selecionarEndereco(hits[0].object)}
function selecionarEndereco(obj){objetosClicaveis.forEach(item=>item.scale.set(1,1,1));obj.scale.set(1.16,1.16,1.16);enderecoSelecionado=obj.userData;atualizarQrPreview(enderecoSelecionado.codigo);document.getElementById('codigoSelecionado').innerHTML=`<b>Código:</b> ${enderecoSelecionado.codigo}<br><b>QR:</b> END-${enderecoSelecionado.codigo}<br><b>Rua:</b> ${enderecoSelecionado.rua}<br><b>Face:</b> F${enderecoSelecionado.face}<br><b>Prateleira:</b> P${pad(enderecoSelecionado.prateleira)}<br><b>Coluna:</b> C${pad(enderecoSelecionado.coluna)}<br><b>Nível:</b> N${enderecoSelecionado.nivel}<br><b>Status:</b> <span style="color:#22c55e;font-weight:900;">${enderecoSelecionado.status}</span><br><br>Este endereço será bipado para guardar ou retirar produto.`;toast(enderecoSelecionado.codigo+' selecionado')}
function resetCamera(){if(!camera||!controls)return;const zoom=Number(document.getElementById('zoomRange')?.value||90)/100;camera.position.set(20/zoom,16/zoom,24/zoom);controls.target.set(0,2.2,0);controls.update()}
function ajustarZoomRange(){const valor=Number(document.getElementById('zoomRange')?.value||90);document.getElementById('zoomTxt').innerText=valor+'%';resetCamera()}
function modoOrbitar(){toast('Modo orbitar ativo: botão esquerdo gira, scroll aproxima.')}
function alternarVisao2D(){visao2DAtiva=!visao2DAtiva;if(visao2DAtiva){camera.position.set(0,42,.01);controls.target.set(0,0,0)}else resetCamera();controls.update()}
function alternarGrades(){gradesAtivas=!gradesAtivas;if(gridHelper)gridHelper.visible=gradesAtivas}
function gerarListaCodigos(){const cfg=lerConfig(),lista=[];for(let face=1;face<=cfg.faces;face++)for(let prateleira=1;prateleira<=cfg.prateleiras;prateleira++)for(let coluna=1;coluna<=cfg.colunas;coluna++)for(let nivel=1;nivel<=cfg.niveis;nivel++)for(let caixa=1;caixa<=cfg.caixas;caixa++)lista.push({rua:cfg.rua,face:`F${face}`,prateleira:`P${pad(prateleira)}`,coluna:`C${pad(coluna)}`,nivel:`N${nivel}`,caixa:cfg.caixas>1?`CX${caixa}`:'',tipo_area:cfg.tipoArea,status:'LIVRE',codigo_curto:codigoEndereco(cfg.rua,face,prateleira,coluna,nivel,caixa)});return lista}
function atualizarResumo(){const cfg=lerConfig(),total=gerarListaCodigos().length;setTexto('infoFaces',cfg.faces);setTexto('infoPrateleiras',cfg.faces*cfg.prateleiras);setTexto('infoColunas',cfg.colunas);setTexto('infoNiveis',cfg.niveis);setTexto('infoEnderecos',total)}
function setTexto(id,valor){const el=document.getElementById(id);if(el)el.innerText=valor}
function preencherTabela(){const listaTotal=gerarListaCodigos(),lista=listaTotal.slice(0,20),tabela=document.getElementById('tabelaCodigos');if(!tabela)return;tabela.innerHTML=`<div style="font-size:12px;color:#6b7280;margin-bottom:8px;font-weight:800;">Total gerado: ${listaTotal.length} endereço(s). Mostrando os primeiros ${lista.length}.</div><table class="table-codes"><thead><tr><th>Código</th><th>Rua</th><th>Face</th><th>Prat.</th><th>Col.</th><th>Nível</th><th>Status</th></tr></thead><tbody>${lista.map(item=>`<tr><td><b>${item.codigo_curto}</b></td><td>${item.rua}</td><td>${item.face}</td><td>${item.prateleira}</td><td>${item.coluna}</td><td>${item.nivel}</td><td><span style="color:#16a34a;font-weight:900;">${item.status}</span></td></tr>`).join('')}</tbody></table>`}
function atualizarQrPreview(codigo){const txt=document.getElementById('qrCodePreview'),box=document.getElementById('qrCodePreviewBox');if(txt)txt.innerText=codigo||'END-';if(!box)return;box.innerHTML='';if(window.QRCode&&codigo){new QRCode(box,{text:'END-'+codigo,width:120,height:120,correctLevel:QRCode.CorrectLevel.M})}else box.innerHTML='<div style="width:120px;height:120px;border:2px solid #111;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:900;">QR</div>'}
function gerarEtiquetas(mostrarAlerta=true){const box=document.getElementById('etiquetasGrid');if(!box)return;const lista=gerarListaCodigos();box.innerHTML=lista.map((item,idx)=>`<div class="etiqueta"><div class="mini-qr" id="qrEtiqueta${idx}"></div><div><strong>ENDEREÇO</strong><br><b>${item.codigo_curto}</b><br><small>${item.rua} • ${item.face} • ${item.prateleira} • ${item.coluna} • ${item.nivel}</small></div></div>`).join('');if(window.QRCode){lista.forEach((item,idx)=>{const alvo=document.getElementById('qrEtiqueta'+idx);if(alvo)new QRCode(alvo,{text:'END-'+item.codigo_curto,width:58,height:58,correctLevel:QRCode.CorrectLevel.M})})}if(mostrarAlerta)alert(`${lista.length} QR Codes gerados para impressão.`)}
function imprimirEtiquetas(){gerarEtiquetas(false);window.print()}
async function cadastrarEnderecos(){const lista=gerarListaCodigos();if(!confirm(`Cadastrar ${lista.length} endereço(s) no sistema?`))return;const banco=db();if(!banco){alert('Banco não carregado. Confira o arquivo supabaseClient.js.');return}const payload=lista.map(item=>({rua:item.rua,face:item.face,prateleira:item.prateleira,coluna:item.coluna,nivel:item.nivel,caixa:item.caixa,tipo_area:item.tipo_area,status:item.status,codigo_curto:item.codigo_curto}));const {error}=await banco.from('enderecamento_estoque').insert(payload);if(error){alert('Erro ao cadastrar endereços: '+error.message);return}alert('Endereços cadastrados com sucesso!')}
function marcarExemplos3D(){objetosClicaveis.forEach((obj,index)=>{obj.userData.status='LIVRE';if(index%17===0){obj.material=new THREE.MeshStandardMaterial({color:0xf97316,roughness:.62});obj.userData.status='OCUPADO'}if(index%31===0){obj.material=new THREE.MeshStandardMaterial({color:0x7c3aed,roughness:.62});obj.userData.status='RESERVADO'}if(index%47===0){obj.material=new THREE.MeshStandardMaterial({color:0xdc2626,roughness:.62});obj.userData.status='BLOQUEADO'}});toast('Exemplos aplicados.')}
function limparLayout(){if(!confirm('Limpar layout 3D da tela?'))return;limparLayout3D();document.getElementById('tabelaCodigos').innerHTML='';document.getElementById('etiquetasGrid').innerHTML='';atualizarQrPreview('');document.getElementById('codigoSelecionado').innerHTML='Clique em uma posição da prateleira.'}
document.addEventListener('DOMContentLoaded',()=>{iniciarThree();simularLayout();atualizarQrPreview('');['rua','faces','prateleiras','colunas','niveis','caixas','tipoArea'].forEach(id=>{const el=document.getElementById(id);if(!el)return;el.addEventListener('change',()=>simularLayout());el.addEventListener('input',()=>simularLayout())})});