/* =========================================================
   ATLAS EXPEDIÇÃO — TRANSFERÊNCIAS / DESMOBILIZAÇÃO
   Responsabilidade: fila patrimonial, despacho, recebimento,
   notificações, rastreabilidade e relatório.
========================================================= */
(function(global){
'use strict';
if(global.AtlasExpedicaoTransferencias?.__loaded)return;
const st={remessas:[],obras:[],selecionados:new Map(),timer:null,usuario:null};
const db=()=>global.client||global.supabaseClient||global.clientSupabase||globalThis.client;
const txt=v=>String(v??'').trim();
const esc=v=>txt(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const user=()=>{try{return JSON.parse(localStorage.getItem('usuario_logado')||'null')||{}}catch(_){return {}}};
const fmt=v=>{if(!v)return '-';const d=new Date(v);return isNaN(d)?txt(v):d.toLocaleString('pt-BR',{timeZone:'America/Cuiaba',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})};
function modal(id,on){const e=document.getElementById(id);if(!e)return;e.classList.toggle('aberto',!!on)}
function permissoes(u=user()){return Array.isArray(u.permissoes)?u.permissoes:String(u.permissoes||'').split(',').map(x=>x.trim()).filter(Boolean)}
function tem(p){const u=user();if(Number(u.id||u.usuario_id)===1)return true; if(global.BDRMenuPermissoes?.temPermissao)return global.BDRMenuPermissoes.temPermissao(p);return permissoes(u).includes(p)||String(u.perfil||'').toUpperCase()==='MASTER'}
function obrasUsuario(){const u=user();if(Number(u.id||u.usuario_id)===1||String(u.perfil||'').toUpperCase()==='MASTER')return null;return new Set([u.obra_id,...String(u.obras_liberadas||'').split(',')].map(x=>String(x||'').trim()).filter(Boolean))}
function obraNome(id){const o=st.obras.find(x=>String(x.id)===String(id));return o?.nome||o?.setor_obra||o?.descricao||`Obra ${id||'-'}`}
async function carregar(){
  const cli=db(); if(!cli)return;
  const [r,o]=await Promise.all([
    cli.from('atlas_patrimonio_remessas').select('*').order('created_at',{ascending:false}).limit(500),
    cli.from('obras').select('id,nome,setor_obra,empresa_id,codigo_obra').order('id')
  ]);
  if(r.error){document.getElementById('trLista')?.replaceChildren();console.warn('Transferências',r.error);return}
  st.remessas=r.data||[]; st.obras=o.data||[]; render();
}
function statusLabel(s){return ({AGUARDANDO_EXPEDICAO:'Aguardando expedição',EM_SEPARACAO:'Em separação',AGUARDANDO_RETIRADA:'Aguardando retirada',EM_TRANSITO:'Em trânsito',RECEBIDA:'Recebida',RECEBIDA_DIVERGENCIA:'Recebida com divergência',CANCELADA:'Cancelada'})[s]||s||'-'}
function statusClass(s){if(s==='EM_TRANSITO')return'transito';if(s==='RECEBIDA')return'recebida';if(s==='RECEBIDA_DIVERGENCIA')return'divergencia';return'aguardando'}
function render(){
 const set=obrasUsuario(),busca=txt(document.getElementById('trBusca')?.value).toLowerCase(),f=txt(document.getElementById('trStatus')?.value)||'ATIVAS',dir=txt(document.getElementById('trDirecao')?.value)||'TODAS';
 const mine=r=>!set||set.has(String(r.obra_origem_id))||set.has(String(r.obra_destino_id));
 let arr=st.remessas.filter(mine);
 document.getElementById('trKpiAguardando')&&(document.getElementById('trKpiAguardando').textContent=arr.filter(r=>['AGUARDANDO_EXPEDICAO','EM_SEPARACAO','AGUARDANDO_RETIRADA'].includes(r.status)).length);
 document.getElementById('trKpiTransito')&&(document.getElementById('trKpiTransito').textContent=arr.filter(r=>r.status==='EM_TRANSITO').length);
 document.getElementById('trKpiRecebidas')&&(document.getElementById('trKpiRecebidas').textContent=arr.filter(r=>r.status==='RECEBIDA').length);
 document.getElementById('trKpiDivergencias')&&(document.getElementById('trKpiDivergencias').textContent=arr.filter(r=>r.status==='RECEBIDA_DIVERGENCIA').length);
 if(f==='ATIVAS')arr=arr.filter(r=>!['RECEBIDA','RECEBIDA_DIVERGENCIA','CANCELADA'].includes(r.status)); else if(f!=='TODAS')arr=arr.filter(r=>r.status===f);
 if(dir==='ORIGEM'&&set)arr=arr.filter(r=>set.has(String(r.obra_origem_id)));if(dir==='DESTINO'&&set)arr=arr.filter(r=>set.has(String(r.obra_destino_id)));
 if(busca)arr=arr.filter(r=>[r.codigo,r.obra_origem_nome,r.obra_destino_nome,r.motorista,r.placa,r.solicitado_por_nome,r.enviado_por_nome].some(v=>txt(v).toLowerCase().includes(busca)));
 const box=document.getElementById('trLista'); if(!box)return;
 if(!arr.length){box.innerHTML='<div class="atlas-transfer-empty">Nenhuma transferência encontrada nesta visão.</div>';return}
 box.innerHTML=arr.map(r=>{const podeDesp=tem('EXPEDICAO_ENTREGAR')&&['AGUARDANDO_EXPEDICAO','EM_SEPARACAO','AGUARDANDO_RETIRADA'].includes(r.status);const podeRec=tem('PATRIMONIO_MOVIMENTAR')&&r.status==='EM_TRANSITO'&&(!set||set.has(String(r.obra_destino_id)));return `<div class="atlas-transfer-card"><div><strong>${esc(r.codigo)}</strong><small>${esc(statusLabel(r.status))}</small></div><div><strong>${esc(r.obra_origem_nome||obraNome(r.obra_origem_id))} → ${esc(r.obra_destino_nome||obraNome(r.obra_destino_id))}</strong><small>${Number(r.total_itens||0)} patrimônio(s) • solicitado por ${esc(r.solicitado_por_nome||r.enviado_por_nome||'-')}</small></div><div><span class="atlas-transfer-status ${statusClass(r.status)}">${esc(statusLabel(r.status))}</span></div><div><strong>${esc(r.motorista||'-')}</strong><small>${esc(r.placa||'')}</small></div><div class="atlas-transfer-actions"><button class="atlas-transfer-btn" onclick="AtlasExpedicaoTransferencias.detalhe(${Number(r.id)})">Abrir</button>${podeDesp?`<button class="atlas-transfer-btn primary" onclick="AtlasExpedicaoTransferencias.abrirDespacho(${Number(r.id)})">Expedir</button>`:''}${podeRec?`<button class="atlas-transfer-btn success" onclick="AtlasExpedicaoTransferencias.abrirReceber(${Number(r.id)})">Receber</button>`:''}</div></div>`}).join('')
}
async function nova(){if(!tem('PATRIMONIO_MOVIMENTAR'))return alert('Você não tem permissão para movimentar patrimônios.');if(!st.obras.length)await carregar();const set=obrasUsuario();const ops=st.obras.filter(o=>!set||set.has(String(o.id))).map(o=>`<option value="${o.id}">${esc((o.id||'')+' - '+(o.nome||o.setor_obra||o.descricao||''))}</option>`).join('');document.getElementById('trNovaOrigem').innerHTML='<option value="">Selecione a origem</option>'+ops;document.getElementById('trNovaDestino').innerHTML='<option value="">Selecione o destino</option>'+st.obras.map(o=>`<option value="${o.id}">${esc((o.id||'')+' - '+(o.nome||o.setor_obra||o.descricao||''))}</option>`).join('');st.selecionados.clear();atualizarResumoNova();document.getElementById('trNovaResultados').innerHTML='<div class="atlas-transfer-empty">Escolha a obra de origem para pesquisar patrimônios.</div>';modal('trNovaModal',true)}
function origemMudou(){st.selecionados.clear();atualizarResumoNova();buscarPatrimonios()}
function agendarBusca(){clearTimeout(st.timer);st.timer=setTimeout(buscarPatrimonios,280)}
async function buscarPatrimonios(){const origem=txt(document.getElementById('trNovaOrigem')?.value),q=txt(document.getElementById('trNovaBusca')?.value);const box=document.getElementById('trNovaResultados');if(!origem){box.innerHTML='<div class="atlas-transfer-empty">Escolha a obra de origem.</div>';return}let query=db().from('patrimonio').select('id,codigo_qr,nome_bem,obra_id,status,tipo,placa,serie').eq('obra_id',Number(origem)).eq('ativo',true).neq('status','EM_TRANSITO').limit(80);if(q)query=query.or(`codigo_qr.ilike.%${q}%,nome_bem.ilike.%${q}%,placa.ilike.%${q}%,serie.ilike.%${q}%`);const {data,error}=await query.order('id',{ascending:false});if(error){box.innerHTML=`<div class="atlas-transfer-empty">${esc(error.message)}</div>`;return}if(!data?.length){box.innerHTML='<div class="atlas-transfer-empty">Nenhum patrimônio encontrado.</div>';return}box.innerHTML=data.map(p=>`<label class="atlas-transfer-pat"><input type="checkbox" ${st.selecionados.has(String(p.id))?'checked':''} onchange='AtlasExpedicaoTransferencias.marcar(${JSON.stringify(p).replaceAll("'","&#39;")},this.checked)'><strong>${esc(p.codigo_qr||'-')}</strong><span>${esc(p.nome_bem||'-')}</span><span>${esc(p.placa||p.serie||'-')}</span><span>${esc(p.status||'-')}</span></label>`).join('')}
function marcar(p,on){if(on)st.selecionados.set(String(p.id),p);else st.selecionados.delete(String(p.id));atualizarResumoNova()}
function atualizarResumoNova(){const e=document.getElementById('trNovaResumo');if(e)e.textContent=st.selecionados.size?`${st.selecionados.size} patrimônio(s) selecionado(s). A Expedição registrará motorista, veículo, placa e saída.`:'Nenhum patrimônio selecionado.'}
function codigo(){const d=new Date();return `TR-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${String(Date.now()).slice(-6)}`}
async function criar(){const origem=txt(document.getElementById('trNovaOrigem')?.value),destino=txt(document.getElementById('trNovaDestino')?.value);if(!origem||!destino)return alert('Selecione origem e destino.');if(origem===destino)return alert('Origem e destino precisam ser diferentes.');if(!st.selecionados.size)return alert('Selecione pelo menos um patrimônio.');const u=user(),oo=st.obras.find(o=>String(o.id)===origem),od=st.obras.find(o=>String(o.id)===destino),sd=txt(document.getElementById('trNovaStatusDestino')?.value);const payload={p_codigo:codigo(),p_empresa_id:Number(oo?.empresa_id||u.empresa_id||17),p_obra_origem_id:Number(origem),p_obra_destino_id:Number(destino),p_obra_origem_nome:oo?.nome||oo?.setor_obra||obraNome(origem),p_obra_destino_nome:od?.nome||od?.setor_obra||obraNome(destino),p_status_destino:sd==='MANTER'?'':sd,p_enviado_por_id:Number(u.id||u.usuario_id||0)||null,p_enviado_por_nome:u.nome||u.usuario||'Usuário não identificado',p_motorista:'',p_veiculo:'',p_placa:'',p_observacao:txt(document.getElementById('trNovaObs')?.value),p_itens:[...st.selecionados.values()].map(p=>({patrimonio_id:Number(p.id)}))};const {data,error}=await db().rpc('atlas_criar_remessa_patrimonial',payload);if(error)return alert('Não foi possível criar a transferência: '+error.message);await notificarExpedicao({...payload,id:data,codigo:payload.p_codigo,total_itens:payload.p_itens.length});modal('trNovaModal',false);await carregar();alert(`Transferência ${payload.p_codigo} enviada para a fila da Expedição.`)}
async function notificarExpedicao(r){try{const {data:us}=await db().from('usuarios').select('id,obra_id,obras_liberadas,permissoes,ativo').eq('ativo',true);const origem=String(r.p_obra_origem_id||r.obra_origem_id),uid=Number(user().id||user().usuario_id);const rows=(us||[]).filter(x=>Number(x.id)!==uid).filter(x=>[x.obra_id,...String(x.obras_liberadas||'').split(',')].map(String).includes(origem)).filter(x=>String(x.permissoes||'').includes('EXPEDICAO')).map(x=>({usuario_destino_id:x.id,empresa_id:r.p_empresa_id||r.empresa_id,tipo:'TRANSFERENCIA_AGUARDANDO_EXPEDICAO',titulo:'↔ Transferência aguardando expedição',mensagem:`${r.codigo||r.p_codigo}: ${r.total_itens||0} patrimônio(s) aguardando expedição.`,link:'atlas.html?m=expedicao&aba=transferencias',lida:false}));if(rows.length)await db().from('notificacoes').insert(rows)}catch(e){console.warn(e)}}
function abrirDespacho(id){const r=st.remessas.find(x=>Number(x.id)===Number(id));if(!r)return;document.getElementById('trDespachoId').value=id;document.getElementById('trMotorista').value=r.motorista||'';document.getElementById('trVeiculo').value=r.veiculo||'';document.getElementById('trPlaca').value=r.placa||'';document.getElementById('trLiberadoPor').value=user().nome||user().usuario||'';document.getElementById('trObsSaida').value='';modal('trDespachoModal',true)}
async function despachar(){const id=Number(document.getElementById('trDespachoId').value),motorista=txt(document.getElementById('trMotorista').value),veiculo=txt(document.getElementById('trVeiculo').value),placa=txt(document.getElementById('trPlaca').value),obs=txt(document.getElementById('trObsSaida').value),u=user();if(!motorista)return alert('Informe quem está entregando / motorista.');if(!placa)return alert('Informe a placa.');const {data,error}=await db().rpc('atlas_despachar_transferencia_patrimonial',{p_remessa_id:id,p_expedido_por_id:Number(u.id||u.usuario_id||0)||null,p_expedido_por_nome:u.nome||u.usuario||'Usuário não identificado',p_motorista:motorista,p_veiculo:veiculo,p_placa:placa,p_observacao_saida:obs||null});if(error)return alert('Não foi possível expedir: '+error.message);modal('trDespachoModal',false);await carregar();const r=st.remessas.find(x=>Number(x.id)===id);await notificarDestino(r||{id});alert(`${Number(data||0)} patrimônio(s) colocados em trânsito.`)}
async function notificarDestino(r){try{if(!r||!r.obra_destino_id)return;const {data:us}=await db().from('usuarios').select('id,obra_id,obras_liberadas,permissoes,ativo').eq('ativo',true);const set=String(r.obra_destino_id),uid=Number(user().id||user().usuario_id);const rows=(us||[]).filter(x=>Number(x.id)!==uid).filter(x=>[x.obra_id,...String(x.obras_liberadas||'').split(',')].map(v=>String(v||'').trim()).includes(set)).filter(x=>String(x.permissoes||'').includes('PATRIMONIO')).map(x=>({usuario_destino_id:x.id,empresa_id:r.empresa_id,tipo:'TRANSFERENCIA_EM_TRANSITO',titulo:'🚚 Transferência patrimonial em trânsito',mensagem:`${r.codigo}: ${r.total_itens||0} patrimônio(s) de ${r.obra_origem_nome||obraNome(r.obra_origem_id)} estão a caminho. Motorista: ${r.motorista||'-'} • Placa: ${r.placa||'-'}.`,link:'atlas.html?m=expedicao&aba=transferencias',lida:false}));if(rows.length){await db().from('notificacoes').insert(rows);document.dispatchEvent(new CustomEvent('atlas:notificacoes:atualizar'))}}catch(e){console.warn('Notificação destino',e)}}
function abrirReceber(id){document.getElementById('trReceberId').value=id;document.getElementById('trCondicao').value='BOA';document.getElementById('trLocalDestino').value='';document.getElementById('trObsRecebimento').value='';modal('trReceberModal',true)}
async function receber(){const id=Number(document.getElementById('trReceberId').value),cond=txt(document.getElementById('trCondicao').value),local=txt(document.getElementById('trLocalDestino').value),obs=txt(document.getElementById('trObsRecebimento').value),u=user();if(cond!=='BOA'&&!obs)return alert('Descreva a avaria ou divergência.');const {data,error}=await db().rpc('atlas_receber_transferencia_patrimonial',{p_remessa_id:id,p_recebido_por_id:Number(u.id||u.usuario_id||0)||null,p_recebido_por_nome:u.nome||u.usuario||'Usuário não identificado',p_condicao:cond,p_observacao_recebimento:obs||null,p_localizacao_destino:local||null});if(error)return alert('Não foi possível receber: '+error.message);modal('trReceberModal',false);await carregar();const r=st.remessas.find(x=>Number(x.id)===id);await notificarOrigem(r,cond);alert(`Recebimento confirmado. ${Number(data||0)} patrimônio(s) transferido(s) para a obra de destino.`)}
async function notificarOrigem(r,cond){try{if(!r)return;const uid=r.solicitado_por_id||r.enviado_por_id;if(!uid)return;await db().from('notificacoes').insert({usuario_destino_id:uid,empresa_id:r.empresa_id,tipo:cond==='BOA'?'TRANSFERENCIA_RECEBIDA':'TRANSFERENCIA_DIVERGENCIA',titulo:cond==='BOA'?'✅ Transferência recebida':'⚠ Transferência recebida com ocorrência',mensagem:`${r.codigo} foi recebida em ${r.obra_destino_nome||obraNome(r.obra_destino_id)}. Condição: ${cond}.`,link:'atlas.html?m=expedicao&aba=transferencias',lida:false})}catch(e){console.warn(e)}}
async function detalhe(id){const r=st.remessas.find(x=>Number(x.id)===Number(id));if(!r)return;const {data:itens,error}=await db().from('atlas_patrimonio_remessa_itens').select('*').eq('remessa_id',id).order('id');if(error)return alert(error.message);document.getElementById('trDetalheTitulo').textContent=`${r.codigo} • ${statusLabel(r.status)}`;const eventos=[['Solicitada',r.solicitado_por_nome||r.enviado_por_nome,r.solicitado_em||r.created_at],['Expedida',r.expedido_por_nome||r.enviado_por_nome,r.enviado_em],['Entregando / motorista',r.motorista,[r.veiculo,r.placa].filter(Boolean).join(' • ')],['Recebida',r.recebido_por_nome,r.recebido_em]].filter(x=>x[1]);document.getElementById('trDetalheConteudo').innerHTML=`<div class="atlas-transfer-grid"><div><label>Origem</label><strong>${esc(r.obra_origem_nome||obraNome(r.obra_origem_id))}</strong></div><div><label>Destino</label><strong>${esc(r.obra_destino_nome||obraNome(r.obra_destino_id))}</strong></div><div><label>Status</label><span>${esc(statusLabel(r.status))}</span></div><div><label>Condição recebimento</label><span>${esc(r.condicao_recebimento||'-')}</span></div><div class="wide"><label>Observações</label><span>${esc([r.observacao,r.observacao_saida,r.observacao_recebimento].filter(Boolean).join(' • ')||'-')}</span></div></div><div class="atlas-transfer-historico">${eventos.map(e=>`<div class="atlas-transfer-evento"><strong>${esc(e[0])}: ${esc(e[1])}</strong><span>${esc(typeof e[2]==='string'&&e[2].includes('•')?e[2]:fmt(e[2]))}</span></div>`).join('')}</div><div style="margin-top:10px"><strong style="font-size:10px">Patrimônios (${(itens||[]).length})</strong>${(itens||[]).map(i=>`<div class="atlas-transfer-evento"><strong>${esc(i.codigo_qr||'-')} • ${esc(i.nome_bem||'-')}</strong><span>${esc(i.recebido?'Recebido':'Pendente')} ${i.condicao_recebimento?'• '+esc(i.condicao_recebimento):''}</span></div>`).join('')}</div><div class="atlas-transfer-actions" style="justify-content:flex-end;margin-top:10px"><button class="atlas-transfer-btn" onclick="AtlasExpedicaoTransferencias.relatorio(${id})">🖨 Relatório</button></div>`;modal('trDetalheModal',true)}
async function relatorio(id){const r=st.remessas.find(x=>Number(x.id)===Number(id));if(!r)return;const {data:itens}=await db().from('atlas_patrimonio_remessa_itens').select('*').eq('remessa_id',id).order('id');const w=open('','_blank');if(!w)return alert('Permita pop-ups para gerar o relatório.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(r.codigo)}</title><style>body{font-family:Arial;padding:28px;color:#111}h1{font-size:20px;color:#a4161a}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.box{border:1px solid #ddd;padding:10px;border-radius:8px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{border:1px solid #ddd;padding:7px;font-size:11px;text-align:left}th{background:#f3f4f6}.assin{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;margin-top:70px}.assin div{border-top:1px solid #333;text-align:center;padding-top:5px;font-size:10px}</style></head><body><h1>Relatório de Transferência Patrimonial</h1><b>${esc(r.codigo)}</b><div class="meta"><div class="box"><b>Origem</b><br>${esc(r.obra_origem_nome||obraNome(r.obra_origem_id))}</div><div class="box"><b>Destino</b><br>${esc(r.obra_destino_nome||obraNome(r.obra_destino_id))}</div><div class="box"><b>Solicitado por</b><br>${esc(r.solicitado_por_nome||'-')} • ${esc(fmt(r.solicitado_em||r.created_at))}</div><div class="box"><b>Expedido por</b><br>${esc(r.expedido_por_nome||r.enviado_por_nome||'-')} • ${esc(fmt(r.enviado_em))}</div><div class="box"><b>Motorista / veículo</b><br>${esc(r.motorista||'-')} • ${esc(r.veiculo||'-')} • ${esc(r.placa||'-')}</div><div class="box"><b>Recebido por</b><br>${esc(r.recebido_por_nome||'-')} • ${esc(fmt(r.recebido_em))}</div></div><table><thead><tr><th>PAT</th><th>Patrimônio</th><th>Status origem</th><th>Recebimento</th><th>Condição</th></tr></thead><tbody>${(itens||[]).map(i=>`<tr><td>${esc(i.codigo_qr||'-')}</td><td>${esc(i.nome_bem||'-')}</td><td>${esc(i.status_origem||'-')}</td><td>${esc(i.recebido?'Sim':'Não')}</td><td>${esc(i.condicao_recebimento||'-')}</td></tr>`).join('')}</tbody></table><div class="assin"><div>Responsável pela origem</div><div>Motorista / transportador</div><div>Responsável pelo recebimento</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function fechar(id){modal(id,false)}
global.AtlasExpedicaoTransferencias={__loaded:true,carregar,render,nova,origemMudou,agendarBusca,marcar,criar,abrirDespacho,despachar,abrirReceber,receber,detalhe,relatorio,fechar};
global.addEventListener('atlas:modulechange',e=>{if(e.detail?.modulo==='expedicao'){const aba=new URLSearchParams(location.search).get('aba');if(aba==='transferencias'){setTimeout(()=>{const b=[...document.querySelectorAll('.atlas-shell-module[data-module="expedicao"] .tab-btn')].find(x=>(x.getAttribute('onclick')||'').includes("'transferencias'"));global.abrirAba?.('transferencias',b)},120)}carregar()}});
console.log('✅ ATLAS EXPEDIÇÃO TRANSFERÊNCIAS carregado');
})(window);
